INSERT INTO features (
    id,
    name,
    description,
    origin_type,
    class_id,
    subclass_id,
    race_id,
    min_character_level,
    is_official,
    created_by_user_id,
    created_at,
    updated_at
) VALUES
(
    gen_random_uuid(),
    'Divine Smite',
    'When you hit a creature with a melee weapon attack, you can expend one spell slot to deal radiant damage to the target, in addition to the weapon''s damage. The extra damage is 2d8 for a 1st-level spell slot, plus 1d8 for each spell level higher than 1st, to a maximum of 5d8. The damage increases by 1d8 if the target is an undead or a fiend.',
    'class',
    'c2000002-0002-4002-8002-000000000007',
    NULL,
    NULL,
    1,
    TRUE,
    NULL,
    now(),
    now()
),
(
    gen_random_uuid(),
    'Lay on Hands',
    'You have a pool of healing power that replenishes when you take a long rest. With that pool, you can restore a total number of hit points equal to your paladin level × 5. As an action, you can touch a creature to restore any number of hit points remaining in the pool, or to cure the target of one disease or neutralize one poison affecting it. You can also expend 5 hit points from your pool of healing to cure the target of one disease or neutralize one poison affecting it.',
    'class',
    'c2000002-0002-4002-8002-000000000007',
    NULL,
    NULL,
    1,
    TRUE,
    NULL,
    now(),
    now()
),
(
    gen_random_uuid(),
    'Fighting Style: Defense',
    'While you are wearing armor, you gain a +1 bonus to AC.',
    'class',
    'c2000002-0002-4002-8002-000000000007',
    NULL,
    NULL,
    1,
    TRUE,
    NULL,
    now(),
    now()
),
(
    gen_random_uuid(),
    'Divine Health',
    'You are immune to disease.',
    'class',
    'c2000002-0002-4002-8002-000000000007',
    NULL,
    NULL,
    1,
    TRUE,
    NULL,
    now(),
    now()
),
(
    gen_random_uuid(),
    'Channel Divinity: Sacred Weapon',
    'As an action, you can use your Channel Divinity to imbue one weapon that you are holding with positive energy. For 1 minute, you add your Charisma modifier to attack rolls made with that weapon (minimum bonus of +1). The weapon also emits bright light in a 20-foot radius and dim light for an additional 20 feet. If the weapon is not already magical, it becomes magical for the duration of this effect.',
    'subclass',
    'c2000002-0002-4002-8002-000000000007',
    '60c56fbf-02f7-4513-abbf-a0402682b757',
    NULL,
    1,
    TRUE,
    NULL,
    now(),
    now()
),
(
    gen_random_uuid(),
    'Channel Divinity: Turn the Unholy',
    'As an action, you can use your Channel Divinity to utter ancient words that are painful for fiends and undead to hear. Each fiend or undead that can hear you within 30 feet of you must make a Wisdom saving throw. If the creature fails its saving throw, it is turned for 1 minute or until it takes damage.',
    'subclass',
    'c2000002-0002-4002-8002-000000000007',
    '60c56fbf-02f7-4513-abbf-a0402682b757',
    NULL,
    1,
    TRUE,
    NULL,
    now(),
    now()
);